import { budgetAccount } from './authority.js';
import { sourceSet } from './mission.js';
import { canonicalHash, canonicalJson, utf8Hash } from './runtime.js';
export const CONTEXT_ROUTES = ['PINNED_ONLY', 'DIRECT', 'FRESH_SCOUT', 'FULL_FORK'];
const hash = /^[a-f0-9]{64}$/;
const pint = (n) => Number.isSafeInteger(n) && n > 0;
const without = (v, k) => { const { [k]: _, ...r } = v; return r; };
const sourceHash = (s) => canonicalHash(s), unique = (v, empty = false) => (empty || v.length > 0) && new Set(v).size === v.length && v.every(x => x.trim());
export function contextDecision(v, e) { if (v.decisionHash !== canonicalHash(without(v, 'decisionHash')) || v.missionId !== e.missionId || v.runId !== e.runId || v.projectId !== e.projectId || v.policyHash !== e.policyHash || v.skillHash !== e.skillHash || v.aiwsHash !== e.aiwsHash || !CONTEXT_ROUTES.includes(v.route) || !pint(v.generation) || !unique(v.allowedSources) || !unique(v.excludedSources, true) || !unique(v.allowedTools) || v.allowedSources.some(x => !e.sourceAllowlist.includes(x) || v.excludedSources.includes(x)) || v.allowedTools.some(x => !e.toolAllowlist.includes(x)))
    throw new TypeError('INVALID_UNAUTHENTICATED_CONTEXT_DECISION'); return Object.freeze({ ...v, allowedSources: Object.freeze([...v.allowedSources]), excludedSources: Object.freeze([...v.excludedSources]), allowedTools: Object.freeze([...v.allowedTools]), budget: budgetAccount(v.budget, e.ceiling) }); }
export function searchPackage(v, e) { const d = e.decision; if (v.hash !== canonicalHash(without(v, 'hash')) || v.decisionHash !== d.decisionHash || v.missionId !== d.missionId || v.runId !== d.runId || v.projectId !== d.projectId || v.generation !== d.generation || v.aiwsHash !== d.aiwsHash || JSON.stringify(v.allowedSources) !== JSON.stringify(d.allowedSources) || JSON.stringify(v.excludedSources) !== JSON.stringify(d.excludedSources) || JSON.stringify(v.sourceOrder) !== JSON.stringify(d.allowedSources) || v.tools.some(x => !d.allowedTools.includes(x)) || !unique(v.questions) || !unique(v.exclusions, true) || !unique(v.sourceOrder) || !unique(v.tools) || v.createdAt > e.now || v.deadline <= e.now || v.deadline - v.createdAt > 1_800_000 || v.authorityOrder.join(',') !== 'rules,wiki,project,memory' || v.maxDepth !== 1 || v.allowRecursion !== false || v.allowMutation !== false || v.allowUser !== false || v.includeRaw !== false)
    throw new TypeError('INVALID_UNAUTHENTICATED_SEARCH_PACKAGE'); const reservation = budgetAccount({ reserved: v.reservation, consumed: { searches: 0, sources: 0, toolCalls: 0, inputTokens: 0, outputTokens: 0, costUsd: 0 } }, e.ceiling).reserved; if (JSON.stringify(reservation) !== JSON.stringify(d.budget.reserved))
    throw new TypeError('PACKAGE_RESERVATION_MISMATCH'); return Object.freeze({ ...v, questions: Object.freeze([...v.questions]), exclusions: Object.freeze([...v.exclusions]), sourceOrder: Object.freeze([...v.sourceOrder]), allowedSources: Object.freeze([...v.allowedSources]), excludedSources: Object.freeze([...v.excludedSources]), tools: Object.freeze([...v.tools]), authorityOrder: Object.freeze([...v.authorityOrder]), reservation }); }
const validCitation = (c, s) => c.excerpt.length > 0 && c.excerptHash === utf8Hash(c.excerpt) && s.some(x => x.ref === c.sourceRef && x.revision === c.sourceRevision && x.sha256 === c.sourceSha256) && c.locator.startsWith(`${c.sourceRef}@${c.sourceRevision}#`);
export function directManifest(v, e) { const s = sourceSet(v.sources), live = sourceSet(e.liveSources); if (v.hash !== canonicalHash(without(v, 'hash')) || v.sourceSetHash !== sourceHash(s) || JSON.stringify(s) !== JSON.stringify(live) || v.missionId !== e.decision.missionId || v.runId !== e.decision.runId || v.projectId !== e.decision.projectId || v.decisionHash !== e.decision.decisionHash || v.generation !== e.decision.generation || !e.queries.includes(v.query) || !v.calls.length || v.calls.some(x => !e.tools.includes(x.tool) || !e.queries.includes(x.query) || x.normalizedArgsHash !== canonicalHash({ tool: x.tool, query: x.query })) || !v.citations.length || v.citations.some(x => !validCitation(x, s)) || v.createdAt > e.now || v.expiresAt <= e.now || v.expiresAt - v.createdAt > 900_000)
    throw new TypeError('INVALID_UNAUTHENTICATED_DIRECT_MANIFEST'); return Object.freeze({ ...v, calls: Object.freeze(v.calls.map(x => Object.freeze({ ...x }))), sources: s, citations: Object.freeze(v.citations.map(x => Object.freeze({ ...x }))), conflicts: Object.freeze([...v.conflicts]), accounting: budgetAccount(v.accounting, e.ceiling) }); }
export function contextCapsule(v, e) { const s = sourceSet(v.sourceSet), live = sourceSet(e.liveSources), max = v.ttlClass === 'VOLATILE' ? 300_000 : v.ttlClass === 'STANDARD' ? 1_800_000 : 86_400_000; if (v.hash !== canonicalHash(without(v, 'hash')) || v.packageHash !== e.packageHash || v.sourceSetHash !== sourceHash(s) || JSON.stringify(s) !== JSON.stringify(live) || v.missionId !== e.decision.missionId || v.runId !== e.decision.runId || v.projectId !== e.decision.projectId || v.decisionHash !== e.decision.decisionHash || v.generation !== e.decision.generation || !pint(v.version) || v.conflictPolicy !== 'PRESERVE' || v.redactionProfile !== e.redactionProfile || v.createdAt > e.now || v.expiresAt <= e.now || v.expiresAt - v.createdAt > max || !v.claims.length || v.claims.some(x => !x.statement.trim() || !validCitation(x, s)))
    throw new TypeError('INVALID_UNAUTHENTICATED_CAPSULE'); return Object.freeze({ ...v, sourceSet: s, claims: Object.freeze(v.claims.map(x => Object.freeze({ ...x }))), conflicts: Object.freeze([...v.conflicts]), accounting: budgetAccount(v.accounting, e.ceiling) }); }
export function forkEvaluation(v, e) { const bytes = Buffer.byteLength(canonicalJson(v.completedPrefix)), minHead = Math.max(2048, Math.ceil(v.contextWindow * .25)), nums = [v.completedPrefixEvents, v.openTurnIndex, v.contextWindow, v.inputTokens, v.outputReserve, v.headroom]; if (v.missionId !== e.missionId || v.runId !== e.runId || v.projectId !== e.projectId || v.authorizationHash !== e.authorizationHash || v.provider !== e.provider || v.model !== e.model || Object.values(v.predicates).some(x => x !== true) || nums.some(x => !Number.isSafeInteger(x) || x < 0) || v.inFlightEvents !== 0 || v.completedPrefixEvents !== v.completedPrefix.length || v.completedPrefixEvents !== v.openTurnIndex || bytes > 32768 || v.contextWindow < 32768 || v.headroom < minHead || v.inputTokens + v.outputReserve + v.headroom > v.contextWindow || v.prefixHash !== canonicalHash(v.completedPrefix))
    throw new TypeError('FULL_FORK_PREDICATE_OR_BOUND_REJECTED'); return Object.freeze({ ...v, completedPrefix: Object.freeze([...v.completedPrefix]), predicates: Object.freeze({ ...v.predicates }) }); }
const admissionKey = (v) => canonicalHash({ missionId: v.missionId, runId: v.runId, generation: v.generation, ordinal: v.ordinal, route: v.route, committedInputHash: v.committedInputHash });
export function contextAdmission(v, e, current, seen) { const s = sourceSet(v.sourceSet), prior = seen.get(v.idempotencyKey); if (!v.admissionId || v.missionId !== e.missionId || v.runId !== e.runId || v.projectId !== e.projectId || v.decisionHash !== e.decisionHash || !pint(v.generation) || !Number.isSafeInteger(v.ordinal) || v.ordinal < 0 || !CONTEXT_ROUTES.includes(v.route) || v.sourceSetHash !== sourceHash(s) || v.admittedHash !== canonicalHash({ decisionHash: v.decisionHash, evidenceHashes: v.evidenceHashes, sourceSetHash: v.sourceSetHash, route: v.route, committedInputHash: v.committedInputHash }) || v.idempotencyKey !== admissionKey(v) || ![v.decisionHash, v.admittedHash, v.sourceSetHash, v.committedInputHash, v.idempotencyKey].every(x => hash.test(x)) || !v.evidenceHashes.length || v.evidenceHashes.some(x => !hash.test(x)) || v.state !== 'COMMITTED' || JSON.stringify(s) !== JSON.stringify(sourceSet(current)))
    throw new TypeError('ADMISSION_INVALID_BEFORE_REPLAY'); if (prior !== undefined && canonicalJson(prior) !== canonicalJson(v))
    throw new TypeError('ADMISSION_REPLAY_CONFLICT'); const authoritative = prior ?? v; return Object.freeze({ ...authoritative, evidenceHashes: Object.freeze([...authoritative.evidenceHashes]), sourceSet: sourceSet(authoritative.sourceSet) }); }
//# sourceMappingURL=context.js.map