export const MISSION_STATES = ['ASSIGNED', 'TRIAGING', 'READY', 'RUNNING', 'WAITING_TIMER', 'WAITING_DEPENDENCY', 'WAITING_SPECIALIST', 'WAITING_HUMAN', 'RETRY_SCHEDULED', 'VERIFYING', 'REWORK', 'HANDOFF_READY', 'PAUSED', 'BLOCKED', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED'];
export const TERMINAL_STATES = ['COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED'];
const NONTERMINAL = MISSION_STATES.filter(x => !TERMINAL_STATES.includes(x));
const fixed = [[null, 'assign', 'ASSIGNED'], ['ASSIGNED', 'begin_triage', 'TRIAGING'], ['TRIAGING', 'start_triage_run', 'RUNNING'], ['RUNNING', 'accept_planning_decision', 'READY'], ['READY', 'start_execution_run', 'RUNNING'], ...['WAITING_TIMER', 'WAITING_DEPENDENCY', 'WAITING_SPECIALIST', 'WAITING_HUMAN', 'RETRY_SCHEDULED'].map(x => ['RUNNING', 'checkpoint_wait', x]), ...['WAITING_TIMER', 'WAITING_DEPENDENCY', 'WAITING_SPECIALIST', 'WAITING_HUMAN', 'RETRY_SCHEDULED'].map(x => [x, 'trigger_satisfied', 'READY']), ['RUNNING', 'submit_for_verification', 'VERIFYING'], ['VERIFYING', 'gate_failed', 'REWORK'], ['VERIFYING', 'gate_failed', 'BLOCKED'], ['REWORK', 'rework_ready', 'READY'], ['VERIFYING', 'gate_passed', 'HANDOFF_READY'], ['HANDOFF_READY', 'complete', 'COMPLETED'], ...['READY', 'WAITING_TIMER', 'WAITING_DEPENDENCY', 'WAITING_SPECIALIST', 'WAITING_HUMAN'].map(x => ['PAUSED', 'resume', x]), ['BLOCKED', 'unblock', 'TRIAGING'], ['BLOCKED', 'unblock', 'READY'], ['FAILED', 'reopen', 'TRIAGING'], ['CANCELLED', 'reopen', 'TRIAGING'], ['EXPIRED', 'reopen', 'TRIAGING']];
for (const s of NONTERMINAL)
    for (const [c, t] of [['pause', 'PAUSED'], ['block', 'BLOCKED'], ['fail', 'FAILED'], ['cancel', 'CANCELLED'], ['expire', 'EXPIRED']])
        fixed.push([s, c, t]);
export const TRANSITION_MATRIX = Object.freeze(fixed.map(([from, command, to]) => Object.freeze({ from, command, to })));
export function assertCommandPreconditions(command, to, p) { const needsGeneration = ['begin_triage', 'start_triage_run', 'start_execution_run', 'trigger_satisfied', 'rework_ready'].includes(command); const needsExecution = command === 'start_execution_run'; const needsArtifacts = command === 'submit_for_verification' || command === 'complete'; const needsGates = command === 'gate_passed' || command === 'complete'; const needsHuman = command === 'reopen' || command === 'unblock'; const needsOwner = command === 'cancel'; const needsActive = command === 'checkpoint_wait' || command === 'submit_for_verification' || command === 'accept_planning_decision'; if ((needsGeneration && !p.claimedGeneration) || (command === 'start_triage_run' && p.purpose !== 'triage') || (needsExecution && (p.purpose !== 'execute' || !p.grantValid || !p.budgetValid)) || (needsArtifacts && !p.artifactsDurable) || (needsGates && !p.gatesPassed) || (needsHuman && !p.humanAuthorized) || (needsOwner && !p.ownerAuthorized) || (needsActive && !p.runActive) || (command === 'complete' && !p.sessionSettled) || (to === 'READY' && !p.claimedGeneration))
    throw new TypeError('TRANSITION_PRECONDITION_FAILED'); }
const hash = /^[a-f0-9]{64}$/;
const positiveInt = (n) => Number.isSafeInteger(n) && n > 0;
export function sourceSet(v) { if (!v.length || v.some(x => !x.ref.trim() || !x.revision.trim() || !hash.test(x.sha256)))
    throw new TypeError('INVALID_SOURCE_SET'); if (new Set(v.map(x => x.ref)).size !== v.length)
    throw new TypeError('DUPLICATE_SOURCE_REF'); return Object.freeze(v.map(x => Object.freeze({ ...x }))); }
export function missionContract(v, e) { if ((e && (v.missionId !== e.missionId || v.projectId !== e.projectId)) || !positiveInt(v.revision) || !v.objective.trim() || !v.projectId.trim() || !v.missionId || !v.agentId || !v.systemSelectors.length || new Set(v.systemSelectors).size !== v.systemSelectors.length || v.systemSelectors.some(x => !x.trim()))
    throw new TypeError('INVALID_OR_FOREIGN_MISSION_CONTRACT'); return Object.freeze({ ...v, systemSelectors: Object.freeze([...v.systemSelectors]), sourceSet: sourceSet(v.sourceSet) }); }
export function missionEvent(v, e) { if (v.missionId !== e.missionId || v.projectId !== e.projectId || !positiveInt(v.seq) || v.priorRevision !== e.currentRevision || v.aggregateRevision !== v.priorRevision + 1 || !v.type.trim() || !hash.test(v.sourceSetHash) || !Number.isSafeInteger(v.occurredAt) || v.occurredAt < 0)
    throw new TypeError('STALE_MALFORMED_OR_FOREIGN_EVENT'); return Object.freeze({ ...v }); }
export function assertTransition(from, command, to, expectedRevision, actualRevision, audit, human = false) { if (!Number.isSafeInteger(expectedRevision) || expectedRevision < 0 || actualRevision !== expectedRevision)
    throw new TypeError('STALE_TRANSITION_REVISION'); if (!audit.actor || ![audit.reason, audit.sourceEventId, audit.correlationId, audit.dedupeKey].every(x => x.trim()) || !audit.evidenceHashes.length || audit.evidenceHashes.some(x => !hash.test(x)))
    throw new TypeError('INVALID_TRANSITION_AUDIT'); if (command === 'reopen' && !human)
    throw new TypeError('REOPEN_REQUIRES_HUMAN'); if (!TRANSITION_MATRIX.some(x => x.from === from && x.command === command && x.to === to))
    throw new TypeError(from && TERMINAL_STATES.includes(from) ? 'TERMINAL_IMMUTABLE' : 'ILLEGAL_TRANSITION'); }
//# sourceMappingURL=mission.js.map