import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';
import { mkdtemp, readFile, realpath as fsRealpath, symlink, writeFile } from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import { createVectorDispatcher, REQUIRED_BINDINGS, runConformance } from '../src/conformance/index.mjs';
import { computePackageImplementationEvidence, loadExecutionPacket, loadPackageDispatcher } from '../src/conformance/runtime.mjs';import { main } from '../src/conformance/cli.mjs';
const H='a'.repeat(64),sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const vectors={format:'gat-conformance-vectors/1',vectors:[{id:'SYN-1',operation:{name:'one',input:{}},expected:{disposition:'allow',reason_code:null,result:'ok'},required_absence:['backend_reads=0'],required_evidence:['trace']},{id:'SYN-2',operation:{name:'two',input:{}},expected:{disposition:'deny',reason_code:'NO_ALLOW_RULE',result:'none'},required_absence:['backend_reads=0'],required_evidence:['audit']}]};
const configFor=document=>({proposal_sha256:H,implementation_sha256:H,environment_fixture_sha256:H,runtime_module_sha256:H,vector_file_sha256:sha(JSON.stringify(document)),vector_count:document.vectors.length});
const executionEvidence={packetPathLiteral:'packet.json',packetPathCanonical:'/fixture/packet.json',packetSha256:H,fixturePathLiteral:'scenario.json',fixturePathCanonical:'/fixture/scenario.json',fixtureSha256:H,bridgePathCanonical:'/package/scenario.mjs',bridgeSha256:H,implementationSha256:H,implementationFiles:['scenario','adapter','memory','policy'].map(name=>({canonicalPath:`/${name}.mjs`,sha256:H})),executionMode:'package-owned-declarative-bridge'};
function binding(vector){return{proposal_sha256:H,vector_file_sha256:H,implementation_sha256:H,policy_revision:1,policy_snapshot_sha256:H,membership_revision:1,membership_snapshot_sha256:H,matched_rule_ids:[],task_execution_binding_sha256:H,working_aip_readiness_evidence_sha256:H,team_plan_approval_sha256:H,native_mission_approval_sha256_or_not_bound:'not_bound',dsh_design_source_version_sha256:H,dsh_runtime_status:'not_integrated',mcp_bridge_status_revision:'not_integrated',partitioned_backend_topology_revision:'memory-v1',selector_sha256_or_not_issued:'not_issued',capability_revision:1,environment_fixture_sha256:H,operation_input:vector.operation,expected_disposition_reason_result:vector.expected,actual_disposition_reason_result:vector.expected,side_effect_counters:{backend_reads:0},audit_event_chain_anchor_sink_results:{events:1},exact_command:'ignored',exit_code:0,started_at:'T0',ended_at:'T1',raw_stdout:'',raw_stderr:'',run_id:'run-1',independent_reviewer:'pending',runtime_module_sha256:H}}
const evidence=vector=>Object.fromEntries(vector.required_evidence.map(item=>[item,{source:'synthetic-fixture',sha256:H,value:{present:true}}]));
const scenarioFixture=(documents=vectors,asserted='tenant/principal/project/agent/owner')=>({format:'gat-conformance-scenario-fixture/1',scenarios:Object.fromEntries(documents.vectors.map(vector=>[vector.id,{steps:[{target:'partition',method:'key',args:{tenantId:'tenant',principalId:'principal',projectScopeId:'project',scopeKind:'agent',scopeOwnerKey:'owner'}}],assertions:[{path:'last',op:'equals',value:asserted}],bindings:binding(vector)}]))});
async function run(document,handler){return runConformance(['--vectors','vectors.json','--evidence','evidence'],{readText:async()=>JSON.stringify(document),makeDir:async()=>{},writeText:async()=>{},dispatch:createVectorDispatcher({'*':handler}),now:()=> 'T',expectedBindings:configFor(document),exactCommand:'outer command',executionEvidence})}

test('strict runner dispatches every vector and preserves literal paths with complete bindings',async()=>{const calls=[],writes=[];const report=await runConformance(['--vectors','fixtures/../synthetic.json','--evidence','.artifacts/literal/hash/'],{readText:async()=>JSON.stringify(vectors),makeDir:async()=>{},writeText:async(p,t)=>writes.push([p,t]),dispatch:createVectorDispatcher({'*':vector=>{calls.push(vector.id);return{status:'pass',actual:vector.expected,bindings:binding(vector),evidence:evidence(vector)}}}),now:()=> 'T',expectedBindings:configFor(vectors),exactCommand:'outer command',executionEvidence});assert.deepEqual(calls,['SYN-1','SYN-2']);assert.equal(report.status,'pass');assert.equal(report.vectorsPathLiteral,'fixtures/../synthetic.json');assert.equal(writes[0][0],'.artifacts/literal/hash/raw-evidence.json');assert.deepEqual(report.executionEvidence,executionEvidence);assert(report.results.every(result=>REQUIRED_BINDINGS.every(key=>Object.hasOwn(result.bindings,key))))});

test('types, expected result, absence and declared evidence fail independently',async()=>{const single={...vectors,vectors:[vectors.vectors[0]]},cases=[vector=>{const b=binding(vector);b.policy_revision='1';return{status:'pass',actual:vector.expected,bindings:b,evidence:evidence(vector)}},vector=>({status:'pass',actual:{...vector.expected,result:'wrong'},bindings:binding(vector),evidence:evidence(vector)}),vector=>{const b=binding(vector);b.side_effect_counters.backend_reads=1;return{status:'pass',actual:vector.expected,bindings:b,evidence:evidence(vector)}}];for(const handler of cases)assert.equal((await run(single,handler)).status,'fail');const missing=await run(single,vector=>({status:'pass',actual:vector.expected,bindings:binding(vector),evidence:{}}));assert.equal(missing.results[0].reason,'DECLARED_EVIDENCE_MISSING')});

test('empty, malformed, duplicate, wrong hash/count and unknown argv fail before dispatch',async()=>{for(const document of [{format:'gat-conformance-vectors/1',vectors:[]},{format:'gat-conformance-vectors/1',vectors:[{id:'bad'}]},{...vectors,vectors:[vectors.vectors[0],vectors.vectors[0]]}]){let called=0;const result=await runConformance(['--vectors','v','--evidence','e'],{readText:async()=>JSON.stringify(document),dispatch:async()=>{called++},expectedBindings:{...configFor(vectors),vector_count:2},exactCommand:'outer',executionEvidence});assert.equal(result.exitCode,2);assert.equal(called,0)}assert.equal((await runConformance(['--vectors','v','--output','e'])).exitCode,2)});

test('packet, declarative fixture and package bridge hashes reject tampering; assertions call real package code',async()=>{const fixtureBytes=Buffer.from(JSON.stringify(scenarioFixture())),bridgeBytes=await readFile(new URL('../src/conformance/scenario.mjs',import.meta.url)),implementation=await computePackageImplementationEvidence(),packetObject={format:'gat-conformance-execution-packet/1',bindings:{proposal_sha256:H,implementation_sha256:implementation.sha256,environment_fixture_sha256:sha(fixtureBytes)},vectors:{pathLiteral:'v',sha256:H,count:2},evidencePathLiteral:'e',exactCommand:'outer',runtime:{fixturePathLiteral:'fixture',fixtureSha256:sha(fixtureBytes),bridgeSha256:sha(bridgeBytes)}},packetBytes=Buffer.from(JSON.stringify(packetObject));const loadedPacket=await loadExecutionPacket({environment:{GAT_CONFORMANCE_EXECUTION_PACKET:'packet',GAT_CONFORMANCE_EXECUTION_PACKET_SHA256:sha(packetBytes)},readBinary:async()=>packetBytes,canonicalize:async value=>value});assert.equal(loadedPacket.packetSha256,sha(packetBytes));await assert.rejects(()=>loadExecutionPacket({environment:{GAT_CONFORMANCE_EXECUTION_PACKET:'packet',GAT_CONFORMANCE_EXECUTION_PACKET_SHA256:H},readBinary:async()=>packetBytes,canonicalize:async value=>value}),/PACKET_HASH_MISMATCH/);const loaded=await loadPackageDispatcher({executionPacket:packetObject,readBinary:async file=>file.endsWith('/fixture')?fixtureBytes:readFile(file),canonicalize:async value=>value});assert.equal((await loaded.dispatch(vectors.vectors[0])).status,'pass');const wrongFixture=Buffer.from(JSON.stringify(scenarioFixture(vectors,'wrong'))),wrongPacket={...packetObject,bindings:{...packetObject.bindings,environment_fixture_sha256:sha(wrongFixture)},runtime:{...packetObject.runtime,fixtureSha256:sha(wrongFixture)}};const wrong=await loadPackageDispatcher({executionPacket:wrongPacket,readBinary:async file=>file.endsWith('/fixture')?wrongFixture:readFile(file),canonicalize:async value=>value});assert.equal((await wrong.dispatch(vectors.vectors[0])).reason,'SCENARIO_ASSERTION_FAILED');await assert.rejects(()=>loadPackageDispatcher({executionPacket:{...packetObject,runtime:{...packetObject.runtime,bridgeSha256:H}},readBinary:async file=>file.endsWith('/fixture')?fixtureBytes:readFile(file),canonicalize:async value=>value}),/BRIDGE_HASH_MISMATCH/)});

test('real packet loader through package bridge and CLI writes pinned raw evidence',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'gat-runner-')),vectorPath=path.join(dir,'synthetic.json'),evidencePath=path.join(dir,'evidence'),fixturePath=path.join(dir,'scenario.json'),fixtureAlias=path.join(dir,'scenario-alias.json'),packetPath=path.join(dir,'packet.json'),packetAlias=path.join(dir,'packet-alias.json'),vectorBytes=Buffer.from(JSON.stringify(vectors)),fixtureBytes=Buffer.from(JSON.stringify(scenarioFixture())),bridgeBytes=await readFile(new URL('../src/conformance/scenario.mjs',import.meta.url)),implementation=await computePackageImplementationEvidence();await writeFile(vectorPath,vectorBytes);await writeFile(fixturePath,fixtureBytes);await symlink(path.basename(fixturePath),fixtureAlias);const outer='pnpm --filter @deepseek-ai/dsh-gat test:conformance -- --vectors literal --evidence literal',packetBytes=Buffer.from(JSON.stringify({format:'gat-conformance-execution-packet/1',bindings:{proposal_sha256:H,implementation_sha256:implementation.sha256,environment_fixture_sha256:sha(fixtureBytes)},vectors:{pathLiteral:vectorPath,sha256:sha(vectorBytes),count:2},evidencePathLiteral:evidencePath,exactCommand:outer,runtime:{fixturePathLiteral:fixtureAlias,fixtureSha256:sha(fixtureBytes),bridgeSha256:sha(bridgeBytes)}}));await writeFile(packetPath,packetBytes);await symlink(path.basename(packetPath),packetAlias);let output='';const code=await main(['--vectors',vectorPath,'--evidence',evidencePath],{environment:{GAT_CONFORMANCE_EXECUTION_PACKET:packetAlias,GAT_CONFORMANCE_EXECUTION_PACKET_SHA256:sha(packetBytes)},writeOut:text=>{output+=text}});assert.equal(code,0);assert.match(output,/"status":"pass"/);const raw=JSON.parse(await readFile(path.join(evidencePath,'raw-evidence.json'),'utf8'));assert.equal(raw.results.length,2);assert.equal(raw.executionEvidence.packetPathLiteral,packetAlias);assert.equal(raw.executionEvidence.packetPathCanonical,await fsRealpath(packetPath));assert.equal(raw.executionEvidence.fixturePathLiteral,fixtureAlias);assert.equal(raw.executionEvidence.fixturePathCanonical,await fsRealpath(fixturePath));assert.match(raw.executionEvidence.bridgePathCanonical,/scenario\.mjs$/);assert.equal(raw.executionEvidence.executionMode,'package-owned-declarative-bridge');assert(raw.results.every(result=>result.bindings.exact_command===outer));let absent='';assert.equal(await main(['--vectors',vectorPath,'--evidence',evidencePath],{environment:{},writeOut:text=>{absent+=text}}),2);assert.match(absent,/ENVIRONMENT_NOT_CONFIGURED/)});
