import { randomUUID } from 'node:crypto';
const RAW_PREFIX='mcp__gat-partitioned-memory-mcp__';
const TOOL_ACTIONS=Object.freeze({gat_memory_search:'memory.search',gat_memory_get:'memory.get',gat_memory_remember:'memory.remember',gat_memory_revise:'memory.revise',gat_memory_tombstone:'memory.tombstone',gat_audit_read:'audit.read'});
const text=v=>typeof v==='string'&&v.length>0&&v.length<=16384;const revision=v=>Number.isSafeInteger(v)&&v>=0;const limit=v=>Number.isSafeInteger(v)&&v>0&&v<=100;
const ARGUMENT_SCHEMAS=Object.freeze({'memory.get':{required:['recordId'],fields:{recordId:text}},'memory.search':{required:['query','limit'],fields:{query:text,limit}},'memory.remember':{required:['content','idempotencyKey'],fields:{content:text,idempotencyKey:text}},'memory.revise':{required:['recordId','patch','expectedRevision','idempotencyKey'],fields:{recordId:text,patch:text,expectedRevision:revision,idempotencyKey:text}},'memory.tombstone':{required:['recordId','expectedRevision','reason','idempotencyKey'],fields:{recordId:text,reason:text,expectedRevision:revision,idempotencyKey:text}},'audit.read':{required:[],fields:{cursor:text,limit}}});
const clone=v=>structuredClone(v);const freeze=v=>{if(v&&typeof v==='object'){for(const x of Object.values(v))freeze(x);Object.freeze(v)}return v};const owned=v=>freeze(clone(v));
function admittedData(action,value){if(!value||Object.getPrototypeOf(value)!==Object.prototype)return null;const schema=ARGUMENT_SCHEMAS[action],keys=Object.keys(value);if(!schema||keys.some(k=>!Object.hasOwn(schema.fields,k))||schema.required.some(k=>!Object.hasOwn(value,k))||keys.some(k=>!schema.fields[k](value[k])))return null;if(action==='memory.remember')return owned({record:{content:value.content},idempotencyKey:value.idempotencyKey});if(action==='memory.revise')return owned({recordId:value.recordId,patch:{content:value.patch},expectedRevision:value.expectedRevision,idempotencyKey:value.idempotencyKey});return owned(Object.fromEntries(keys.map(k=>[k,value[k]])))}
function denied(code='ACCESS_DENIED'){return owned({status:'denied',code,result:null})}
function referenceResult(value){if(!value||typeof value!=='object')return owned({trust:'untrusted_reference',provenance:null,value});const record=value.record??value;return owned({trust:'untrusted_reference',provenance:{recordId:record.recordId??null,revision:record.revision??null,evidenceHash:record.evidenceHash??null,sourceRefs:record.sourceRefs??[]},value});}
export class GatMemoryAdapter{
 #policy;#mcp;#capability;#revision;#denials;#verify;
 constructor({policy,mcpClient,capabilityRevision,selectorVerifier,denialSink=()=>{}}){if(!policy||typeof policy.authorize!=='function'||!mcpClient||typeof mcpClient.execute!=='function'||typeof selectorVerifier!=='function'||!Number.isSafeInteger(capabilityRevision)||capabilityRevision<0)throw new TypeError('adapter configuration invalid');this.#policy=policy;this.#mcp=mcpClient;this.#capability=Object.freeze({kind:'gat.private.mcp-capability',nonce:randomUUID()});this.#revision=capabilityRevision;this.#denials=denialSink;this.#verify=selectorVerifier}
 visibleTools(){return Object.freeze(Object.keys(TOOL_ACTIONS))}
 #deny(reasonCode,code='ACCESS_DENIED'){try{this.#denials(owned({reasonCode}))}catch{}return denied(code)}
 invoke(tool,args,trusted){if(typeof tool!=='string'||tool.toLocaleLowerCase('en-US').startsWith(RAW_PREFIX)){return this.#deny('RAW_MCP_TOOL_NOT_ADMITTED','RAW_MCP_TOOL_NOT_ADMITTED')}const action=TOOL_ACTIONS[tool];if(!action)return this.#deny('CAPABILITY_UNSUPPORTED','CAPABILITY_UNSUPPORTED');const data=admittedData(action,args);if(!data)return this.#deny('BINDING_INVALID','BINDING_INVALID');if(!trusted||trusted.capabilityRevision!==this.#revision||!trusted.requestBase)return this.#deny('CAPABILITY_UNSUPPORTED','CAPABILITY_UNSUPPORTED');const request=owned({...trusted.requestBase,action,correlationId:trusted.correlationId,resource:{...trusted.requestBase.resource,resourceId:data.recordId??trusted.requestBase.resource.resourceId}});let decision;try{decision=this.#policy.authorize(request)}catch{return this.#deny('SECURITY_SERVICE_UNAVAILABLE')}if(!decision||typeof decision!=='object')return this.#deny('POLICY_RESULT_INVALID');if(decision.status==='denied')return decision;if(decision.status!=='allowed')return this.#deny('POLICY_RESULT_INVALID');const s=decision.selector;if(!s||typeof s!=='object'||!decision.decision||typeof decision.decision!=='object')return this.#deny('POLICY_RESULT_INVALID','BINDING_INVALID');let verified=false;try{verified=this.#verify(s)}catch{}if(!verified||decision.decision?.selectorHash!==s.selectorHash||s.correlationId!==trusted.correlationId||s.decisionId!==decision.decision?.decisionId||s.issuedAt!==decision.decision?.decidedAt||s.action!==action||s.resourceId!==(args.recordId??trusted.requestBase.resource.resourceId)||s.capabilityRevision!==this.#revision||s.tenantId!==trusted.requestBase.subject.tenantId||s.principalId!==trusted.requestBase.subject.principalId||s.projectScopeId!==trusted.requestBase.subject.projectScopeId||s.scopeKind!==trusted.requestBase.resource.scopeKind||s.scopeOwnerKey!==trusted.requestBase.resource.scopeOwnerKey||!Array.isArray(s.classificationConstraints)||s.classificationConstraints.length!==1||s.classificationConstraints[0]!==trusted.requestBase.resource.classification)return this.#deny('SELECTOR_BINDING_INVALID','BINDING_INVALID');const authority=owned({selector:s,correlationId:s.correlationId,decisionId:s.decisionId,issuedAt:s.issuedAt,capabilityRevision:s.capabilityRevision});let result;try{result=this.#mcp.execute(this.#capability,action,data,authority)}catch{return this.#deny('SECURITY_SERVICE_UNAVAILABLE')}return owned({status:'allowed',code:'ALLOW_EXPLICIT',reference:referenceResult(result)});}
}
export const RAW_MCP_PREFIX=RAW_PREFIX;
