export interface PolicyEvidence { policyRevision:number; policySnapshotHash:string; membershipRevision:number; membershipSnapshotHash:string; readinessEvidenceHash:string; teamPlanRevision:number; teamPlanApprovedRevision:number; teamPlanApprovalHash:string; nativeMissionRevision?:number; nativeMissionApprovedRevision?:number; nativeMissionApprovalHash?:string; accountMappingRevision:number; accountMappingHash:string; taskExecutionBindingHash:string; capabilityRevision:number; capabilityHash:string; classificationPolicyHash:string }
export interface PolicyRequest { subject:{tenantId:string;principalId:string;agentId:string;projectScopeId:string;taskId:string;aipId:string;workspaceId:string;accountRegistryId:string;workspaceRoot:string;workspacePath:string}; resource:{tenantId:string;principalId:string;projectScopeId:string;scopeKind:'agent'|'project-desk'|'task';scopeOwnerKey:string;classification:'public'|'internal'|'restricted';resourceId?:string}; action:string;correlationId:string;evidence:PolicyEvidence }
export interface DeniedPolicyResult {status:'denied';code:'ACCESS_DENIED';result:null}
export interface AllowedPolicyResult {status:'allowed';code:'ALLOW_EXPLICIT';selector:Readonly<Record<string,unknown>>;decision:Readonly<Record<string,unknown>>}
export declare function computeAccountMappingHash(mapping:Record<string,unknown>):string;
export declare function computePolicySnapshotHash(snapshot:Record<string,unknown>):string;
export declare function verifySelector(selector:Record<string,unknown>,key:string|Buffer):boolean;
export declare class DenyFirstPolicy{constructor(options:{snapshotProvider:()=>Record<string,unknown>;observerSink?:(event:Readonly<Record<string,unknown>>)=>void;timing:{now:()=>number;delay:(milliseconds:number)=>void;minimumMs:number;maximumMs:number};selectorSigningKey:string|Buffer;selectorKeyId?:string;wallClock?:()=>string});committedAdmissions():ReadonlyArray<Readonly<Record<string,unknown>>>;authorize(request:PolicyRequest):DeniedPolicyResult|AllowedPolicyResult}
export{DenyFirstPolicy as PolicyEngine};
