export type JsonObject={readonly[key:string]:unknown};
export interface ConformanceExpected{readonly disposition:string;readonly reason_code:string|null;readonly result:string}
export interface ConformanceVector{readonly id:string;readonly operation:Readonly<{name:string;input:JsonObject}>;readonly expected:ConformanceExpected;readonly required_absence:ReadonlyArray<string>;readonly required_evidence:ReadonlyArray<string>}
export interface DeclaredEvidence{readonly source:string;readonly sha256:string;readonly value:unknown}
export interface ConformanceDispatchResult{readonly status:'pass'|'fail';readonly reason?:string;readonly actual:ConformanceExpected|null;readonly bindings:Readonly<Record<string,unknown>>;readonly evidence:Readonly<Record<string,DeclaredEvidence>>}
export type ConformanceDispatch=(vector:ConformanceVector)=>ConformanceDispatchResult|Promise<ConformanceDispatchResult>;
export interface ExpectedBindings{readonly proposal_sha256:string;readonly implementation_sha256:string;readonly environment_fixture_sha256:string;readonly runtime_module_sha256:string;readonly vector_file_sha256:string;readonly vector_count:number}
export interface ExecutionEvidence{readonly packetPathLiteral:string;readonly packetPathCanonical:string;readonly packetSha256:string;readonly fixturePathLiteral:string;readonly fixturePathCanonical:string;readonly fixtureSha256:string;readonly bridgePathCanonical:string;readonly bridgeSha256:string;readonly implementationSha256:string;readonly implementationFiles:ReadonlyArray<Readonly<{canonicalPath:string;sha256:string}>>;readonly executionMode:'package-owned-declarative-bridge'}
export interface ConformanceDependencies{readText?:(file:string)=>Promise<string>;makeDir?:(directory:string)=>Promise<unknown>;writeText?:(file:string,text:string)=>Promise<unknown>;dispatch?:ConformanceDispatch;now?:()=>string;stdout?:string;stderr?:string;exactCommand:string;expectedBindings:ExpectedBindings;executionEvidence:ExecutionEvidence}
export interface ConformanceExecutedReport{readonly format:'gat-conformance-raw-evidence/1';readonly status:'pass'|'fail';readonly exitCode:0|1;readonly[other:string]:unknown}
export interface ConformanceEarlyFailure{readonly format?:never;readonly status:'fail';readonly exitCode:2;readonly reason:string;readonly[other:string]:unknown}
export type ConformanceReport=ConformanceExecutedReport|ConformanceEarlyFailure;
export declare const REQUIRED_BINDINGS:ReadonlyArray<string>;export declare function parseArguments(argv:string[]):Readonly<{vectors:string;evidence:string}>;export declare function createVectorDispatcher(handlers:Record<string,ConformanceDispatch>):ConformanceDispatch;export declare function runConformance(argv:string[],dependencies:ConformanceDependencies):Promise<Readonly<ConformanceReport>>;
