#!/usr/bin/env python3
"""Claude sub-agent shim generator (CR-AIWS-2026-08-007 T2).

Generates `.claude/agents/<desk_id>.md` from an agent task desk (formerly agent instance):
identity from `instance.yaml` + run_policy + pointers. The shim is a GENERATED ARTIFACT —
hand edits are overwritten on the next regenerate (create/clone/rename/upgrade hooks).

The tool NEVER spawns an agent and NEVER calls an LLM (§8D invariant). Writes ONLY under
`<project_root>/.claude/agents/`. Refuses to overwrite a file it did not generate
(missing GENERATED marker) — a hand-authored Claude agent is not clobbered.

Run with `py build_agent_shims.py --desk <id> | --all [--project-root PATH]`.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    sys.stderr.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

DEV_ROOT = Path(__file__).resolve().parent.parent          # pack root
_DEFAULT_PROJECT_ROOT = DEV_ROOT.parent.parent             # holds .ai-work/ + .claude/
# CR-AIWS-2026-08-006 P2 dual-read
_DESKS_NEW = DEV_ROOT / "agents" / "task_desks"
_DESKS_OLD = DEV_ROOT / "agents" / "instances"
INSTANCES = _DESKS_NEW if _DESKS_NEW.is_dir() else _DESKS_OLD

# CR-AIWS-2026-08-074 C12 — the shim builder enumerates desks too, so it needs the same desk-root
# guard as run_agent.py: `--all` against a half-visible desk set writes a half-complete shim set and
# reports success. IMPORTED, not re-implemented — this file already carries a second copy of the
# resolve logic above, and duplicated rename-sensitive logic is the exact defect this CR closes out.
# run_agent.py sits in this same directory (sys.path[0] when run as a script; tests insert the pack
# tooling dir). No try/except fallback on purpose: a guard that quietly fails to load is worse than
# no guard, because it still looks like it is guarding.
from run_agent import DeskRootAmbiguous, enforce_desk_root  # noqa: E402

GENERATED_MARKER = "GENERATED by build_agent_shims.py"
_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_\-]{0,79}$")
# Default whitelist: worker tools only — `Agent` is EXCLUDED BY DESIGN (no chaining, Phase-1 rule).
DEFAULT_TOOLS = ["Read", "Grep", "Glob", "Bash", "Edit", "Write", "TodoWrite"]


def _desk_yaml_path(inst_dir: Path) -> Path:
    """CR-006 P2: desk.yaml (new) dual-read fallback instance.yaml."""
    p = inst_dir / "desk.yaml"
    return p if p.exists() else inst_dir / "instance.yaml"


def _read(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8")
    except OSError:
        return ""


def _yaml_top(txt: str, key: str) -> str:
    m = re.search(rf"(?m)^{key}:[ \t]*([^#\n]*?)[ \t]*(?:#.*)?$", txt)
    return (m.group(1).strip().strip('"').strip("'")) if m else ""


def _yaml_nested(txt: str, key: str) -> str:
    m = re.search(rf"(?m)^[ \t]+{key}:[ \t]*([^#\n]*?)[ \t]*(?:#.*)?$", txt)
    return (m.group(1).strip().strip('"').strip("'")) if m else ""


def _tools_whitelist(inst_yaml: str) -> list[str]:
    raw = _yaml_nested(inst_yaml, "tools_whitelist") or _yaml_top(inst_yaml, "tools_whitelist")
    tools = [t.strip() for t in raw.split(",") if t.strip()] if raw else list(DEFAULT_TOOLS)
    if "Agent" in tools:
        print(f"  [warn] tools_whitelist declared 'Agent' — stripped (no chaining, CR-2026-08-007)")
        tools = [t for t in tools if t != "Agent"]
    return tools


def _shim_text(desk_id: str, inst_dir: Path, project_root: Path) -> str:
    yml = _read(_desk_yaml_path(inst_dir))
    display = _yaml_top(yml, "display_name") or desk_id
    blueprint = _yaml_top(yml, "blueprint_id") or _yaml_nested(yml, "blueprint_id") or "(custom)"
    executor = _yaml_nested(yml, "executor") or "main_session"
    tools = _tools_whitelist(yml)
    desk_rel = inst_dir.resolve().relative_to(project_root.resolve()).as_posix()
    desc = (f"{display} — AIWS agent task desk '{desk_id}' (ATDB: {blueprint}). "
            "Spawn ONLY via the AIWS dispatch flow: run_agent.py start rc=0 (gates passed) "
            "then the main session dispatches with a 3-block brief. Not for ad-hoc use.")
    body = f"""---
name: {desk_id}
description: {desc}
tools: {", ".join(tools)}
---

<!-- {GENERATED_MARKER} (CR-AIWS-2026-08-007) from {desk_rel}/desk.yaml + its ATDB.
     Do NOT hand-edit — regenerate via `py <pack>/tooling/build_agent_shims.py --desk {desk_id}`. -->

You are **{display}**, the agent working at AIWS agent task desk `{desk_id}`.

## Your Task Desk (state lives here, not in you)
- Desk: `{desk_rel}/` — identity `desk.yaml`, memory `memory/`, process `process/`, queue `training/`.
- Load the desk via its **scoped-load policy** (digest + hints — AP-CR-26/CR-017). Do NOT read the whole desk.
- executor: {executor} (this shim is used when a run dispatches with `run_policy.executor: claude_subagent`).

## Before working
1. Read the dispatch brief you were given (3-block: context digest + step info + hand-off contract).
2. Read the run's ARC (path in the brief) and the Task Workspace surfaces it points to.
3. Follow YOUR desk process (`{desk_rel}/process/`) — governance_invariant steps are non-negotiable.

## Conduct (binding)
- **Stop-on-self-deviation** (CR-AIWS-2026-08-002): if you notice you are deviating from a declared
  rule/policy (run_policy, non_responsibilities, boundary, governance_invariant, the driving AIP),
  STOP, record it, and return `blocked` with the question — never self-adjudicate and continue.
- **Capture routing** (CR-AIWS-2026-08-010): personal lessons → desk `learning_candidates.jsonl`;
  project/task/wiki/AIWS captures → Task Workspace `08_capture_inbox.jsonl`; unsure → Task Workspace.
- No auto-promotion (memory/wiki/blueprint are HUMAN-gated). Honor your desk's non_responsibilities.
- Write ONLY inside the Task Workspace / your run folder. Never dispatch other agents.

## Return (hand-off contract — this IS your final message)
Summary + self-assessment + suggested-next (REWORK vs ADVANCE) + POINTERS to what you wrote
(04_findings / 05_open_questions / mailbox / 08_capture_inbox / output files). Do NOT restate
workspace content. If blocked: state the question + `decision_class`; answers arrive via mailbox
`messages_in.jsonl` on resume.
"""
    return body


def _generate(desk_id: str, project_root: Path) -> bool:
    inst_dir = INSTANCES / desk_id
    if not inst_dir.is_dir():
        print(f"  [error] desk '{desk_id}' not found under {INSTANCES}")
        return False
    if not _ID_RE.match(desk_id):
        print(f"  [error] desk id '{desk_id}' fails id validation")
        return False
    out_dir = project_root / ".claude" / "agents"
    out = out_dir / f"{desk_id}.md"
    if out.exists() and GENERATED_MARKER not in _read(out):
        print(f"  [error] {out} exists and is NOT a generated shim — refusing to overwrite")
        return False
    new = _shim_text(desk_id, inst_dir, project_root)
    if not new.strip():
        print(f"  [error] refusing to write empty shim for '{desk_id}'")
        return False
    out_dir.mkdir(parents=True, exist_ok=True)
    out.write_text(new, encoding="utf-8", newline="\n")
    print(f"  shim written: {out}")
    return True


def main() -> int:
    p = argparse.ArgumentParser(description="Generate Claude sub-agent shims from agent task desks")
    p.add_argument("--desk", default="", help="desk id (instance folder name)")
    p.add_argument("--all", action="store_true", help="regenerate shims for every desk")
    p.add_argument("--project-root", default="", help="project root (default: pack-root/../..)")
    ns = p.parse_args()
    # CR-AIWS-2026-08-074 C12 — refuse an ambiguous desk root before generating anything.
    try:
        enforce_desk_root()
    except DeskRootAmbiguous as e:
        raise SystemExit(f"error: {e}")
    project_root = Path(ns.project_root).resolve() if ns.project_root else _DEFAULT_PROJECT_ROOT
    if not ns.desk and not ns.all:
        p.error("pass --desk <id> or --all")
    desks = ([d.name for d in sorted(INSTANCES.iterdir()) if d.is_dir()]
             if ns.all else [ns.desk])
    ok = True
    for d in desks:
        ok = _generate(d, project_root) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
